version: '3'
services:
  registration-service:
    build: registration-service
    image: microservice/registration-service
    ports:
      - 1111:1111
  accounts-service:
    build: accounts-service
    image: microservice/accounts-service
    restart: always
    ports:
      - 2222:2222
    depends_on:
      - registration-service
  web-service:
    build: web-service
    image: microservice/web-service
    restart: always
    ports:
      - 3333:3333
    depends_on:
      - registration-service
      - accounts-service
