FROM java:8-jre
MAINTAINER Vaibhav Sood <vaibhavsood12@gmail.com>

ADD ./target/registration-service-0.0.1-SNAPSHOT.jar /

CMD ["java", "-Xmx200m", "-jar", "/registration-service-0.0.1-SNAPSHOT.jar"]

EXPOSE 1111