FROM java:8-jre
MAINTAINER Vaibhav Sood <vaibhavsood12@gmail.com>

ADD ./target/accounts-service-0.0.1-SNAPSHOT.jar /

CMD ["java", "-Xmx200m", "-jar", "/accounts-service-0.0.1-SNAPSHOT.jar"]

EXPOSE 2222